version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234  # Required to initialize MySQL
      MYSQL_DATABASE: kiii-data
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: demo:latest
    depends_on:
      - db
    ports:
      - "8080:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/kiii-data?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234

volumes:
  mysql-data:
